#!/data/data/com.termux/files/usr/bin/sh
aa='\033[1;31m'
a='\033[1;32m'
b='\033[1;33m'
c='\033[1;34m'
d='\033[1;35m'
e='\033[1;36m'
f='\033[1;90m'
g='\033[1;91m'
h='\033[1;92m'
i='\033[1;93m'
j='\033[1;94m'
k='\033[1;95m'
l='\033[1;96m'
echo " "
echo " "
sleep 2
echo "$a Repack hone wala hai $b"
echo " "
echo "$c Repack Ho Rha Hai $d"
echo " "
sleep 2
cd Maruf/Port
tsu -c ./.repackimg.sh
cd ..
cd Stock
tsu -c ./.repackimg.sh

